name: Deploy to Vercel

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Show Vercel CLI version
        run: vercel --version

      - name: Login to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          echo "Logging in with Vercel token..."
          vercel login --token=$VERCEL_TOKEN

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_TELEMETRY_DISABLED: 1

        run: |
          echo "Starting deployment..."
          vercel --prod --yes --token=$VERCEL_TOKEN